version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartordermanagement-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartordermanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - smartorder_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartordermanagement-api
    ports:
      - "8080:8080" # Porta da API
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=smartordermanagement;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - smartorder_net

volumes:
  postgres-data:

networks:
  smartorder_net:
    external: true
