version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartordermanagement-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - smartorder_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartordermanagement-api
    ports:
      - "8080:8080" # Porta da API
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - smartorder_net

volumes:
  postgres-data:

networks:
  smartorder_net:
