// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartOrderManagement.Infrastructure.Data.Context;

#nullable disable

namespace SmartOrderManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SmartOrderManagementDbContext))]
    [Migration("20260720222304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SmartOrderManagement.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Observation");

                    b.Property<string>("Ordered")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Ordered");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<int>("Table")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Table");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("Time");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
